from __future__ import annotations

import argparse
import os
from decimal import Decimal
from pathlib import Path

from .catalog import read_releases_csv, search_releases, write_releases_csv
from .env import load_env_file
from .http_client import DiscogsClient, DiscogsHttpError
from .inventory_api import InventorySearchProgress, refresh_seller_watchlist_entries, search_seller_inventory_offers
from .io import read_albums, read_offers, write_marketplace_links_html, write_offers_csv, write_offers_template_csv
from .marketplace import marketplace_rows
from .marketplace_scraper import merge_scrape_results, scrape_marketplace_offers, scrape_marketplace_search_offers
from .optimizer import OptimisationError, optimise_purchases
from .reports import write_options_html, write_options_json
from .sellers import enrich_seller_ratings
from .audit import audit_purchase_outputs, write_audit_html, write_audit_json
from .seller_watchlist import (
    build_seller_watchlist_from_offer_files,
    checked_now_utc,
    read_seller_watchlist,
    write_seller_watchlist,
)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        load_env_file(getattr(args, "env_file", None))
        if args.command == "search":
            return run_search(args)
        if args.command == "optimize":
            return run_optimize(args)
        if args.command == "scrape":
            return run_scrape(args)
        if args.command == "api-sellers":
            return run_api_sellers(args)
        if args.command == "build-watchlist":
            return run_build_watchlist(args)
        if args.command == "refresh-watchlist":
            return run_refresh_watchlist(args)
        if args.command == "audit":
            return run_audit(args)
        if args.command == "run":
            search_code = run_search(args)
            if args.offers:
                optimize_code = run_optimize(args)
                return max(search_code, optimize_code)
            print("No offers CSV provided; generated catalog candidates and marketplace links only.")
            print("Full cost optimisation needs an offers CSV with item price, shipping, seller, and listing URL.")
            return search_code
        parser.error("Unknown command")
        return 2
    except (FileNotFoundError, ValueError, DiscogsHttpError, OptimisationError) as exc:
        print(f"Error: {exc}")
        return 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Find UK Discogs vinyl candidates and optimise purchases from seller offers."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    for command in ("search", "optimize", "run", "scrape", "api-sellers", "audit"):
        subparser = subparsers.add_parser(command)
        if command == "audit":
            subparser.add_argument("--albums", required=True, help="CSV with artist, album, and optional release_id.")
            subparser.add_argument("--offers", required=True, help="Scraped or manually collected offers CSV.")
            subparser.add_argument("--options", required=True, help="purchase_options.json to audit.")
            subparser.add_argument("--out-dir", default="outputs", help="Directory for generated audit reports.")
            continue
        add_common_args(subparser)
        if command in {"optimize", "run"}:
            subparser.add_argument("--offers", help="CSV containing eligible marketplace offers.")
        if command in {"optimize", "run", "scrape", "api-sellers"}:
            subparser.add_argument("--top", type=int, default=5, help="Number of purchase options to output.")
            subparser.add_argument(
                "--max-offers-per-album",
                type=int,
                default=12,
                help="Limit offers per album before optimisation to keep runtime bounded.",
            )
            subparser.add_argument(
                "--beam-width",
                type=int,
                default=5000,
                help="Number of partial purchase combinations retained during optimisation.",
            )
            subparser.add_argument(
                "--no-enrich-sellers",
                action="store_true",
                help="Do not call GET /users/{seller} to fill missing seller rating/review counts.",
            )
        if command in {"search", "run", "scrape", "api-sellers"}:
            subparser.add_argument("--per-album", type=int, default=5, help="Release candidates per album.")
        if command == "scrape":
            subparser.add_argument(
                "--releases",
                help="CSV generated by search. Defaults to <out-dir>/releases.csv; searched if missing.",
            )
            subparser.add_argument(
                "--pages-per-condition",
                type=int,
                default=1,
                help="Marketplace pages to scrape per release and media condition.",
            )
            subparser.add_argument(
                "--marketplace-source",
                choices=("release", "search", "both"),
                default="both",
                help="Scrape release-specific pages, direct marketplace search pages, or both.",
            )
            subparser.add_argument(
                "--skip-optimize",
                action="store_true",
                help="Only write offers_scraped.csv, without creating purchase option reports.",
            )
        if command == "api-sellers":
            subparser.add_argument(
                "--seller-watchlist",
                default="data/seller_watchlist.csv",
                help="CSV of seller usernames to query through GET /users/{seller}/inventory.",
            )
            subparser.add_argument(
                "--seller-limit",
                type=int,
                default=100,
                help="Maximum number of sellers from the watchlist to query.",
            )
            subparser.add_argument(
                "--min-seller-rating",
                type=Decimal,
                default=Decimal("99.00"),
                help="Minimum seller rating to use from the watchlist.",
            )
            subparser.add_argument(
                "--min-seller-reviews",
                type=int,
                default=500,
                help="Minimum seller review count to use from the watchlist.",
            )
            subparser.add_argument(
                "--per-query",
                type=int,
                default=10,
                help="Inventory results to fetch per seller/album query.",
            )
            subparser.add_argument(
                "--max-pages-per-query",
                type=int,
                default=1,
                help="Inventory pages to fetch per seller/album query.",
            )
            subparser.add_argument(
                "--skip-optimize",
                action="store_true",
                help="Only write offers_api.csv, without creating purchase option reports.",
            )
    watchlist_parser = subparsers.add_parser("build-watchlist")
    watchlist_parser.add_argument("--offers", nargs="+", required=True, help="Offer CSV files used only as seller seeds.")
    watchlist_parser.add_argument("--out", default="data/seller_watchlist.csv", help="Output seller watchlist CSV.")
    watchlist_parser.add_argument("--min-rating", type=Decimal, default=Decimal("99.00"))
    watchlist_parser.add_argument("--min-reviews", type=int, default=500)
    watchlist_parser.add_argument("--max-sellers", type=int, default=200)

    refresh_parser = subparsers.add_parser("refresh-watchlist")
    refresh_parser.add_argument("--seller-watchlist", default="data/seller_watchlist.csv")
    refresh_parser.add_argument("--out", help="Output CSV. Defaults to updating --seller-watchlist.")
    refresh_parser.add_argument("--min-rating", type=Decimal, default=Decimal("99.00"))
    refresh_parser.add_argument("--min-reviews", type=int, default=500)
    refresh_parser.add_argument("--max-sellers", type=int, default=200)
    refresh_parser.add_argument("--env-file", help="Optional local env file, e.g. .env.")
    refresh_parser.add_argument("--token-env", default="DISCOGS_USER_TOKEN")
    refresh_parser.add_argument("--user-agent", default="DiscogsVinylOptimizer/0.1")
    refresh_parser.add_argument("--api-delay-seconds", type=float, default=1.5)
    return parser


def add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--albums", required=True, help="CSV with artist, album, and optional release_id.")
    parser.add_argument("--out-dir", default="outputs", help="Directory for generated reports.")
    parser.add_argument("--env-file", help="Optional local env file, e.g. .env.")
    parser.add_argument(
        "--token-env",
        default="DISCOGS_USER_TOKEN",
        help="Environment variable containing an optional Discogs user token.",
    )
    parser.add_argument(
        "--user-agent",
        default="DiscogsVinylOptimizer/0.1",
        help="User-Agent sent to the Discogs API.",
    )
    parser.add_argument(
        "--api-delay-seconds",
        type=float,
        default=1.5,
        help="Minimum delay between Discogs API GET calls.",
    )


def run_search(args: argparse.Namespace) -> int:
    albums = read_albums(args.albums)
    client = make_client(args)
    all_candidates = []
    warnings = []
    for album in albums:
        try:
            candidates = search_releases(client, album, per_album=args.per_album)
        except DiscogsHttpError as exc:
            warnings.append(f"{album.display}: {exc}")
            candidates = []
        all_candidates.extend(candidates)

    out_dir = Path(args.out_dir)
    releases_path = out_dir / "releases.csv"
    links_path = out_dir / "marketplace_links.html"
    offers_template_path = out_dir / "offers_template.csv"
    write_releases_csv(all_candidates, releases_path)
    write_marketplace_links_html(marketplace_rows(all_candidates, albums), links_path)
    write_offers_template_csv(albums, offers_template_path)
    print(f"Wrote {releases_path}")
    print(f"Wrote {links_path}")
    print(f"Wrote {offers_template_path}")
    for warning in warnings:
        print(f"Warning: {warning}")
    return 0 if not warnings else 1


def run_optimize(args: argparse.Namespace) -> int:
    if not args.offers:
        raise ValueError("--offers is required for optimize")
    albums = read_albums(args.albums)
    offers = read_offers(args.offers)
    warnings = []
    if not args.no_enrich_sellers:
        offers, seller_warnings = enrich_seller_ratings(make_client(args), offers)
        warnings.extend(seller_warnings)
    options = optimise_purchases(
        albums=albums,
        offers=offers,
        top_n=args.top,
        max_offers_per_album=args.max_offers_per_album,
        beam_width=args.beam_width,
    )

    out_dir = Path(args.out_dir)
    html_path = out_dir / "purchase_options.html"
    json_path = out_dir / "purchase_options.json"
    write_options_html(options, html_path, warnings=warnings)
    write_options_json(options, json_path)
    print(f"Wrote {html_path}")
    print(f"Wrote {json_path}")
    for warning in warnings:
        print(f"Warning: {warning}")
    return 0


def run_scrape(args: argparse.Namespace) -> int:
    albums = read_albums(args.albums)
    out_dir = Path(args.out_dir)
    releases_path = Path(args.releases) if args.releases else out_dir / "releases.csv"

    if args.marketplace_source in {"release", "both"} and not releases_path.exists():
        print(f"{releases_path} not found; searching Discogs catalog first.")
        search_code = run_search(args)
        if search_code != 0:
            return search_code

    scrape_results = []
    if args.marketplace_source in {"release", "both"}:
        candidates = read_releases_csv(releases_path, albums)
        scrape_results.append(
            scrape_marketplace_offers(
                candidates=candidates,
                pages_per_condition=args.pages_per_condition,
                user_agent=args.user_agent,
            )
        )
    if args.marketplace_source in {"search", "both"}:
        scrape_results.append(
            scrape_marketplace_search_offers(
                albums=albums,
                pages_per_condition=args.pages_per_condition,
                user_agent=args.user_agent,
            )
        )
    scrape_result = merge_scrape_results(*scrape_results)
    offers_path = out_dir / "offers_scraped.csv"
    write_offers_csv(scrape_result.offers, offers_path)
    print(f"Wrote {offers_path}")
    print(f"Scraped {len(scrape_result.offers)} eligible offer(s).")
    for warning in scrape_result.warnings:
        print(f"Warning: {warning}")

    if args.skip_optimize:
        return 0 if scrape_result.offers else 1
    if not scrape_result.offers:
        return 1

    offers = scrape_result.offers
    warnings = list(scrape_result.warnings)
    if not args.no_enrich_sellers:
        offers, seller_warnings = enrich_seller_ratings(make_client(args), offers)
        warnings.extend(seller_warnings)

    options = optimise_purchases(
        albums=albums,
        offers=offers,
        top_n=args.top,
        max_offers_per_album=args.max_offers_per_album,
        beam_width=args.beam_width,
    )
    html_path = out_dir / "purchase_options.html"
    json_path = out_dir / "purchase_options.json"
    write_options_html(options, html_path, warnings=warnings)
    write_options_json(options, json_path)
    print(f"Wrote {html_path}")
    print(f"Wrote {json_path}")
    return 0


def run_api_sellers(args: argparse.Namespace) -> int:
    if not os.environ.get(args.token_env):
        raise ValueError(
            f"{args.token_env} is required for api-sellers because Discogs returns shipping prices only in an authenticated GET context."
        )
    albums = read_albums(args.albums)
    sellers = read_seller_watchlist(
        args.seller_watchlist,
        min_rating=args.min_seller_rating,
        min_reviews=args.min_seller_reviews,
        limit=args.seller_limit,
    )
    if not sellers:
        raise ValueError("No sellers matched the watchlist thresholds.")

    out_dir = Path(args.out_dir)
    checkpoint_path = out_dir / "inventory_checkpoint.json"
    print(f"Inventory checkpoint: {checkpoint_path}")
    client = make_client(args)
    result = search_seller_inventory_offers(
        client=client,
        albums=albums,
        sellers=sellers,
        per_query=args.per_query,
        max_pages_per_query=args.max_pages_per_query,
        catalog_per_album=args.per_album,
        checkpoint_path=checkpoint_path,
        progress_callback=print_inventory_progress,
    )

    offers_path = out_dir / "offers_api.csv"
    write_offers_csv(result.offers, offers_path)
    print(f"Wrote {offers_path}")
    print(f"Queried {len(sellers)} seller(s) from {args.seller_watchlist}.")
    print(f"Found {len(result.offers)} eligible API offer(s).")
    for warning in result.warnings:
        print(f"Warning: {warning}")

    if args.skip_optimize:
        return 0 if result.offers else 1
    if not result.offers:
        return 1

    options = optimise_purchases(
        albums=albums,
        offers=result.offers,
        top_n=args.top,
        max_offers_per_album=args.max_offers_per_album,
        beam_width=args.beam_width,
    )
    html_path = out_dir / "purchase_options.html"
    json_path = out_dir / "purchase_options.json"
    audit_html_path = out_dir / "audit_report.html"
    audit_json_path = out_dir / "audit_report.json"
    write_options_html(options, html_path, warnings=result.warnings)
    write_options_json(options, json_path)
    audit = audit_purchase_outputs(args.albums, offers_path, json_path)
    write_audit_html(audit, audit_html_path)
    write_audit_json(audit, audit_json_path)
    print(f"Wrote {html_path}")
    print(f"Wrote {json_path}")
    print(f"Wrote {audit_html_path}")
    print(f"Wrote {audit_json_path}")
    print("Audit result: " + ("PASS" if audit.passed else "FAIL"))
    return 0 if audit.passed else 1


def run_build_watchlist(args: argparse.Namespace) -> int:
    entries = build_seller_watchlist_from_offer_files(
        paths=args.offers,
        min_rating=args.min_rating,
        min_reviews=args.min_reviews,
        max_sellers=args.max_sellers,
    )
    write_seller_watchlist(entries, args.out)
    print(f"Wrote {args.out}")
    print(f"Watchlist sellers: {len(entries)}")
    return 0


def run_refresh_watchlist(args: argparse.Namespace) -> int:
    if not os.environ.get(args.token_env):
        raise ValueError(f"{args.token_env} is required to refresh seller ratings through the Discogs API.")
    entries = read_seller_watchlist(
        args.seller_watchlist,
        min_rating=args.min_rating,
        min_reviews=args.min_reviews,
        limit=args.max_sellers,
    )
    client = make_client(args)
    refreshed, warnings = refresh_seller_watchlist_entries(client, entries, checked_now_utc())
    output_path = args.out or args.seller_watchlist
    write_seller_watchlist(refreshed, output_path)
    print(f"Wrote {output_path}")
    print(f"Refreshed sellers: {len(refreshed)}")
    for warning in warnings:
        print(f"Warning: {warning}")
    return 0 if not warnings else 1


def run_audit(args: argparse.Namespace) -> int:
    result = audit_purchase_outputs(args.albums, args.offers, args.options)
    out_dir = Path(args.out_dir)
    html_path = out_dir / "audit_report.html"
    json_path = out_dir / "audit_report.json"
    write_audit_html(result, html_path)
    write_audit_json(result, json_path)
    print(f"Wrote {html_path}")
    print(f"Wrote {json_path}")
    print("Audit result: " + ("PASS" if result.passed else "FAIL"))
    for failure in result.failures:
        print(f"Failure: {failure}")
    return 0 if result.passed else 1


def make_client(args: argparse.Namespace) -> DiscogsClient:
    token = os.environ.get(args.token_env)
    return DiscogsClient(token=token, user_agent=args.user_agent, min_delay_seconds=args.api_delay_seconds)


def print_inventory_progress(progress: InventorySearchProgress) -> None:
    action = "Skipped" if progress.skipped else "Completed"
    seller_delta = "" if progress.skipped else f", +{progress.seller_offers} offer(s)"
    print(
        f"{action} seller {progress.current_seller}/{progress.total_sellers}: "
        f"{progress.seller}{seller_delta}, {progress.total_offers} total offer(s), "
        f"{progress.warnings} warning(s), elapsed {format_duration(progress.elapsed_seconds)}",
        flush=True,
    )


def format_duration(seconds: float) -> str:
    total_seconds = int(seconds)
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours}h{minutes:02d}m{seconds:02d}s"
    return f"{minutes}m{seconds:02d}s"
